spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root  # 数据库用户名
    password: BLESSEDwmm320  # 数据库密码
    url: jdbc:mysql://localhost:3306/jpa_and_rest?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 当修改实体时，对应可以修改更新表结构
    show-sql: true  # 是否展示SQL
    database: mysql
    open-in-view: true